.PHONY: all
GTEX?=
MARIAN?=

all: missalette-booklet.pdf pew-sheet-booklet.pdf

%.pdf: %.tex
	env openout_any=a latexmk --pdflatex=lualatex --pdf $<

%.gtex: %.gabc
	openout_any=a gregorio $< -o $@

%-booklet.pdf: %.pdf
	pdfjam --landscape --suffix booklet --booklet true $<

[% for fn in ["introit", "gradual" if gradual, alleluia, "sequentia" if sequentia, "offertory", "communion"] if fn %]
[[fn]].gtex: [[fn]].gabc
GTEX += [[fn]].gtex
[% endfor %]

[% for fn in ["kyrie", "gloria" if gloria, "sanctus", "agnus", "ite"] if fn %]
[[masses_path]]/[[mass_setting]]/[[fn]].gtex: [[masses_path]]/[[mass_setting]]/[[fn]].gabc
GTEX += [[masses_path]]/[[mass_setting]]/[[fn]].gtex
[% endfor %]

[% if creedp %]
[[creed_path]]/[[creed]]/credo.gtex: [[creed_path]]/[[creed]]/credo.gabc
GTEX += [[creed_path]]/[[creed]]/credo.gtex
[% endif %]

[% for fn in ["amen", asperges, "dominus-vobiscum", "pax-domini", "preface_" ~ preface, "sed-libera-nos", "sequenti"] if fn %]
[[common_tones_path]]/[[rite]]/[[fn]].gtex: [[common_tones_path]]/[[rite]]/[[fn]].gabc
GTEX += [[common_tones_path]]/[[rite]]/[[fn]].gtex
[% endfor %]

[% if marian %]
[[marian_path]]/[[rite]]/[[marian_type]].gtex: [[marian_path]]/[[rite]]/[[marian_type]].gabc
MARIAN += [[marian_path]]/[[rite]]/[[marian_type]].gtex
MARIAN += [[marian_path]]/[[marian_type]]_resp.tex
[% endif %]

missalette.pdf: missalette.tex propers.tex styling.sty rubrics.sty titlepage.sty ${GTEX} ${MARIAN}

missalette-booklet.pdf: missalette.pdf

pew-sheet.pdf: pew-sheet.tex propers.tex styling.sty rubrics.sty ${MARIAN}

pew-sheet-booklet.pdf: pew-sheet.pdf


clean:
	find . -maxdepth 1 -name '*latexmk' -delete
	find . -maxdepth 1 -name '*.gtex' -delete
	find . -maxdepth 1 -name '*.fls' -delete
	find . -maxdepth 1 -name '*.log' -delete
	find . -maxdepth 1 -name '*.aux' -delete
	find . -maxdepth 1 -name '*.gaux' -delete
